/*
 * Copyright (c) 2022 Vinzenz Malke
 * SPDX-License-Identifier:  Apache-2.0
*/

#pragma once

typedef uint32_t rplidar_result;

#define RPLIDAR_RESULT_OK                       0
#define RPLIDAR_RESULT_FAIL_BIT                 0x80000000

#define RPLIDAR_RESULT_INVALID_RESPONSE_HEADER  (0x8001 | RPLIDAR_RESULT_FAIL_BIT)
#define RPLIDAR_RESULT_INVALID_RESPONSE_TYPE    (0x8002 | RPLIDAR_RESULT_FAIL_BIT)
#define RPLIDAR_RESULT_TX_HANDLER_BUSY          (0x8003 | RPLIDAR_RESULT_FAIL_BIT)
#define RPLIDAR_RESULT_RX_HANDLER_BUSY          (0x8004 | RPLIDAR_RESULT_FAIL_BIT)
#define RPLIDAR_RESULT_TX_TIMEOUT               (0x8005 | RPLIDAR_RESULT_FAIL_BIT)
#define RPLIDAR_RESULT_RX_TIMEOUT               (0x8006 | RPLIDAR_RESULT_FAIL_BIT)
#define RPLIDAR_RESULT_DEVICE_UNHEALTHY         (0x8007 | RPLIDAR_RESULT_FAIL_BIT)

#define RPLIDAR_IS_OK(x)    ( ((x) & RPLIDAR_RESULT_FAIL_BIT) == 0 )
#define RPLIDAR_IS_FAIL(x)  ( ((x) & RPLIDAR_RESULT_FAIL_BIT) )
