/*
 * Copyright (c) 2022-2026 Vinzenz Malke, Tilmann Unte
 * SPDX-License-Identifier:  Apache-2.0
*/

#pragma once

#include "rplidar_protocol.h"
// Commands without payload and response

#define RPLIDAR_CMD_STOP            0x25
#define RPLIDAR_CMD_RESET           0x40

// Commands without payload; with single response

#define RPLIDAR_CMD_GET_INFO        0x50
#define RPLIDAR_CMD_GET_HEALTH      0x52
#define RPLIDAR_CMD_GET_SAMPLERATE  0x59

// Commands without payload; with multi reponse

#define RPLIDAR_CMD_SCAN            0x20
#define RPLIDAR_CMD_FORCE_SCAN      0x21

// Commands with payload

#define RPLIDAR_CMD_EXPRESS_SCAN    0x82    // multi response
#define RPLIDAR_CMD_GET_CONFIG      0x84    // single response


#define RPLIDAR_CONFIG_RESPONSE_TYPE_SIZE   4
#define RPLIDAR_CONFIG_REQUEST_TYPE_SIZE    4

#define RPLIDAR_REQUESTTYPE_CONF_SCAN_MODE_COUNT            0x70
#define RPLIDAR_REQUESTTYPE_CONF_SCAN_MODE_US_PER_SAMPLE    0x71
#define RPLIDAR_REQUESTTYPE_CONF_SCAN_MODE_MAX_DISTANCE     0x74
#define RPLIDAR_REQUESTTYPE_CONF_SCAN_MODE_ANS_TYPE         0x75
#define RPLIDAR_REQUESTTYPE_CONF_SCAN_MODE_TYPICAL          0x7C
#define RPLIDAR_REQUESTTYPE_CONF_SCAN_MODE_NAME             0x7F

#define RPLIDAR_REQUESTPAYLOADSIZE_CONF_SCAN_MODE_COUNT            0
#define RPLIDAR_REQUESTPAYLOADSIZE_CONF_SCAN_MODE_US_PER_SAMPLE    2
#define RPLIDAR_REQUESTPAYLOADSIZE_CONF_SCAN_MODE_MAX_DISTANCE     2
#define RPLIDAR_REQUESTPAYLOADSIZE_CONF_SCAN_MODE_ANS_TYPE         2
#define RPLIDAR_REQUESTPAYLOADSIZE_CONF_SCAN_MODE_TYPICAL          0
#define RPLIDAR_REQUESTPAYLOADSIZE_CONF_SCAN_MODE_NAME             2

#define RPLIDAR_RESPONSEPAYLOADSIZE_CONF_SCAN_MODE_COUNT            2
#define RPLIDAR_RESPONSEPAYLOADSIZE_CONF_SCAN_MODE_US_PER_SAMPLE    4
#define RPLIDAR_RESPONSEPAYLOADSIZE_CONF_SCAN_MODE_MAX_DISTANCE     4
#define RPLIDAR_RESPONSEPAYLOADSIZE_CONF_SCAN_MODE_ANS_TYPE         1
#define RPLIDAR_RESPONSEPAYLOADSIZE_CONF_SCAN_MODE_TYPICAL          2
#define RPLIDAR_RESPONSEPAYLOADSIZE_CONF_SCAN_MODE_NAME             5  //max of 16, we will cap this to have constant length

enum rplidar_scan_idx {
    RPLIDAR_SCAN_MODE_DEFAULT,
    RPLIDAR_SCAN_MODE_FORCE,
    RPLIDAR_SCAN_MODE_EXPRESS,
    RPLIDAR_SCAN_MODE_COUNT
};

enum rplidar_scan_values {
    RPLIDAR_SCAN_MODE_COMMAND,
    RPLIDAR_SCAN_MODE_RESPONSE_TYPE,
    RPLIDAR_SCAN_MODE_RESPONSE_SIZE
};

static const uint8_t rplidar_scan_modes[RPLIDAR_SCAN_MODE_COUNT][3] = {
    [RPLIDAR_SCAN_MODE_DEFAULT] = {
        RPLIDAR_CMD_SCAN,
        RPLIDAR_RESP_TYPE_MEASUREMENT,
        sizeof(rplidar_resp_measurement_node_t)
    },
    [RPLIDAR_SCAN_MODE_FORCE] = {
        RPLIDAR_CMD_FORCE_SCAN,
        RPLIDAR_RESP_TYPE_MEASUREMENT,
        sizeof(rplidar_resp_measurement_node_t)
    },
    [RPLIDAR_SCAN_MODE_EXPRESS] = {
        RPLIDAR_CMD_EXPRESS_SCAN,
        RPLIDAR_RESP_TYPE_EM_LEGACY,
        sizeof(rplidar_resp_express_measurement_t)
    }
};

enum rplidar_get_config_idx {
    RPLIDAR_CONF_SCAN_MODE_COUNT,           
    RPLIDAR_CONF_SCAN_MODE_US_PER_SAMPLE,   
    RPLIDAR_CONF_SCAN_MODE_MAX_DISTANCE,    
    RPLIDAR_CONF_SCAN_MODE_ANS_TYPE,        
    RPLIDAR_CONF_SCAN_MODE_TYPICAL,         
    RPLIDAR_CONF_SCAN_MODE_NAME,
    RPLIDAR_CONF_TYPECOUNT           
};

enum rplidar_conf_values {
    RPLIDAR_CONF_REQUESTTYPE,
    RPLIDAR_CONF_REQUESTPAYLOADSIZE,
    RPLIDAR_CONF_RESPONSEPAYLOADSIZE
};

static const uint8_t rplidar_conf_types[RPLIDAR_CONF_TYPECOUNT][3] = {
	[RPLIDAR_CONF_SCAN_MODE_COUNT] = {
		RPLIDAR_REQUESTTYPE_CONF_SCAN_MODE_COUNT,
        RPLIDAR_REQUESTPAYLOADSIZE_CONF_SCAN_MODE_COUNT,
        RPLIDAR_RESPONSEPAYLOADSIZE_CONF_SCAN_MODE_COUNT
	},
    [RPLIDAR_CONF_SCAN_MODE_US_PER_SAMPLE] = {    
        RPLIDAR_REQUESTTYPE_CONF_SCAN_MODE_US_PER_SAMPLE,    
        RPLIDAR_REQUESTPAYLOADSIZE_CONF_SCAN_MODE_US_PER_SAMPLE,    
        RPLIDAR_RESPONSEPAYLOADSIZE_CONF_SCAN_MODE_US_PER_SAMPLE  
    },
    [RPLIDAR_CONF_SCAN_MODE_MAX_DISTANCE] = {
        RPLIDAR_REQUESTTYPE_CONF_SCAN_MODE_MAX_DISTANCE,
        RPLIDAR_REQUESTPAYLOADSIZE_CONF_SCAN_MODE_MAX_DISTANCE,
        RPLIDAR_RESPONSEPAYLOADSIZE_CONF_SCAN_MODE_MAX_DISTANCE
    },
    [RPLIDAR_CONF_SCAN_MODE_ANS_TYPE] = {
        RPLIDAR_REQUESTTYPE_CONF_SCAN_MODE_ANS_TYPE,         
        RPLIDAR_REQUESTPAYLOADSIZE_CONF_SCAN_MODE_ANS_TYPE,        
        RPLIDAR_RESPONSEPAYLOADSIZE_CONF_SCAN_MODE_ANS_TYPE
    },
    [RPLIDAR_CONF_SCAN_MODE_TYPICAL] = {
        RPLIDAR_REQUESTTYPE_CONF_SCAN_MODE_TYPICAL,
        RPLIDAR_REQUESTPAYLOADSIZE_CONF_SCAN_MODE_TYPICAL,
        RPLIDAR_RESPONSEPAYLOADSIZE_CONF_SCAN_MODE_TYPICAL
    },
    [RPLIDAR_CONF_SCAN_MODE_NAME] = {
        RPLIDAR_REQUESTTYPE_CONF_SCAN_MODE_NAME,
        RPLIDAR_REQUESTPAYLOADSIZE_CONF_SCAN_MODE_NAME,
        RPLIDAR_RESPONSEPAYLOADSIZE_CONF_SCAN_MODE_NAME
    }
};


#define RPLIDAR_RESP_MEASUREMENT_ANGLE_SHIFT    1
#define RPLIDAR_RESP_MEASUREMENT_CHECKBIT	1
#define RPLIDAR_RESP_MEASUREMENT_QUALITY_SHIFT  2
#define RPLIDAR_RESP_MEASUREMENT_SYNCBIT        (0x1)
#define RPLIDAR_RESP_MEASUREMENT_INVERTSYNCBIT  (0x2)
#define RPLIDAR_RESP_MEASUREMENT_INVERTSYNCSHIFT  1
