# Copyright (c) 2025-2026 Tilmann Unte
# SPDX-License-Identifier:  Apache-2.0

# Native Sim specific Settings
CONFIG_ASAN=y
CONFIG_UBSAN=y

# Verify that this works?
CONFIG_SYS_CLOCK_TICKS_PER_SEC=10000
