# Copyright (c) 2025-2026 Tilmann Unte
# SPDX-License-Identifier:  Apache-2.0

# Activate UART serial connection (Debug, Magni, RPLIDAR)
CONFIG_SERIAL=y
CONFIG_UART_INTERRUPT_DRIVEN=y

# Native Sim specific Settings
CONFIG_ASAN=y
CONFIG_UBSAN=y
#CONFIG_COVERAGE=y

#CONFIG_SYS_CLOCK_TICKS_PER_SEC=100000

################################################################################
# Include Magni Driver
CONFIG_APPLICATION_DEFINED_SYSCALL=y
CONFIG_UR_MAGNI_DRIVER=y

# Include Slamtech RPLidar Driver
CONFIG_RPLIDAR=y
